server:
  port: 8763

spring:
 application:
  name: microservice-discovery-eureka

erueka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
security:
  basic:
    enable: true
  user:
    name: user
    password: password123